spring.application.name: application-status

server.port: 8080

spring.cloud.stream.bindings.statusEvent-in-0:
  destination: application-status
  consumer:
    default.value.serde: se.kf.stream.kafkastream.serde.StatusEventSerde

# Common kafka configuration
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9092
  deserializationExceptionHandler: logAndContinue
  applicationId: ${spring.application.name}-cg
  configuration:
    application.server: localhost:8080
    allow.auto.create.topics: false
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    commit.interval.ms: 1000
    security.protocol: PLAINTEXT
